In [12]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
df.drop(columns = 'Id')

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder()

In [6]:
x = df.iloc[:,:-1]
y = df['Species']

In [7]:
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [13]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2, random_state = 1)

lg = LogisticRegression()
lg.fit(xtrain, ytrain)
ypred = lg.predict(xtest)

In [11]:
from sklearn.metrics import classification_report

print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# PCA

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [15]:
sc = StandardScaler()

x = sc.fit_transform(x)
x

array([[-1.72054204e+00, -9.00681170e-01,  1.03205722e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.69744751e+00, -1.14301691e+00, -1.24957601e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.67435299e+00, -1.38535265e+00,  3.37848329e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-1.65125846e+00, -1.50652052e+00,  1.06445364e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.62816394e+00, -1.02184904e+00,  1.26346019e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.60506942e+00, -5.37177559e-01,  1.95766909e+00,
        -1.17067529e+00, -1.05003079e+00],
       [-1.58197489e+00, -1.50652052e+00,  8.00654259e-01,
        -1.34127240e+00, -1.18150376e+00],
       [-1.55888037e+00, -1.02184904e+00,  8.00654259e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.53578584e+00, -1.74885626e+00, -3.56360566e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.51269132e+00, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00

In [17]:
pca = PCA()
pcs = pca.fit_transform(x)
pcs

array([[-2.81633893e+00,  5.06050643e-01, -3.69150782e-01,
         1.86404027e-01, -2.61185709e-02],
       [-2.64552745e+00, -6.51799379e-01, -5.14570643e-01,
         1.63013571e-01, -1.06467767e-01],
       [-2.87948066e+00, -3.21035860e-01, -2.08181466e-01,
         2.76983890e-01, -3.10964467e-02],
       [-2.81093445e+00, -5.77363207e-01, -1.92960814e-01,
         3.24545021e-01,  6.27180247e-02],
       [-2.87988351e+00,  6.70467643e-01, -1.65234705e-01,
         2.06334760e-01,  3.48144445e-02],
       [-2.59317599e+00,  1.51881921e+00, -2.44262301e-01,
         2.81464512e-01, -7.82727977e-03],
       [-2.90159154e+00,  6.77106952e-02,  7.68232449e-02,
         4.21125433e-01,  3.45259603e-02],
       [-2.71013857e+00,  2.44822135e-01, -2.52998315e-01,
         1.40009940e-01,  2.32224184e-02],
       [-2.78572445e+00, -1.10033691e+00, -7.81773113e-02,
         2.98947341e-01,  2.37816197e-02],
       [-2.64728182e+00, -4.51017611e-01, -3.59239650e-01,
         1.20810769e-02

In [18]:
np.cumsum(pca.explained_variance_ratio_)

array([0.7470533 , 0.93140587, 0.97823211, 0.99587979, 1.        ])

In [20]:
pca = PCA(n_components = 2)
pcs = pca.fit_transform(x)
pcs

array([[-2.81633893e+00,  5.06050643e-01],
       [-2.64552745e+00, -6.51799379e-01],
       [-2.87948066e+00, -3.21035860e-01],
       [-2.81093445e+00, -5.77363207e-01],
       [-2.87988351e+00,  6.70467643e-01],
       [-2.59317599e+00,  1.51881921e+00],
       [-2.90159154e+00,  6.77106952e-02],
       [-2.71013857e+00,  2.44822135e-01],
       [-2.78572445e+00, -1.10033691e+00],
       [-2.64728182e+00, -4.51017611e-01],
       [-2.62045947e+00,  1.06753291e+00],
       [-2.74530029e+00,  1.51688686e-01],
       [-2.64364170e+00, -7.13641450e-01],
       [-2.99135307e+00, -9.51363109e-01],
       [-2.60680324e+00,  1.88447264e+00],
       [-2.64545824e+00,  2.71378247e+00],
       [-2.58707757e+00,  1.50604525e+00],
       [-2.56129243e+00,  5.06790365e-01],
       [-2.29803185e+00,  1.42857788e+00],
       [-2.67103437e+00,  1.14621464e+00],
       [-2.29017648e+00,  4.27049021e-01],
       [-2.52906562e+00,  9.41927041e-01],
       [-3.01331841e+00,  4.68455142e-01],
       [-2.

In [21]:
data = pd.DataFrame(pcs, columns = ['PCA1','PCA2'])
data

PCA1      PCA2
0   -2.816339  0.506051
1   -2.645527 -0.651799
2   -2.879481 -0.321036
3   -2.810934 -0.577363
4   -2.879884  0.670468
..        ...       ...
145  2.424421  0.377119
146  2.164220 -0.915696
147  2.139796  0.254272
148  2.029480  0.998725
149  1.674835 -0.046213

[150 rows x 2 columns]

In [22]:
data['Species'] = y
data

PCA1      PCA2  Species
0   -2.816339  0.506051        0
1   -2.645527 -0.651799        0
2   -2.879481 -0.321036        0
3   -2.810934 -0.577363        0
4   -2.879884  0.670468        0
..        ...       ...      ...
145  2.424421  0.377119        2
146  2.164220 -0.915696        2
147  2.139796  0.254272        2
148  2.029480  0.998725        2
149  1.674835 -0.046213        2

[150 rows x 3 columns]

In [23]:
x = data.iloc[:,:2]
y = data['Species']

In [24]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.2, random_state = 1)

In [25]:
lg = LogisticRegression()
lg.fit(xtrain, ytrain)
ypred = lg.predict(xtest)

print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

